# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import psutil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(872, 585)
        MainWindow.setMinimumSize(QtCore.QSize(872, 585))
        MainWindow.setMaximumSize(QtCore.QSize(872, 585))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setToolTipDuration(-1)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(84, 128))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameLeft = QtWidgets.QFrame(self.centralwidget)
        self.frameLeft.setGeometry(QtCore.QRect(0, -30, 171, 611))
        self.frameLeft.setAutoFillBackground(True)
        self.frameLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.treeWidget = QtWidgets.QTreeWidget(self.frameLeft)
        self.treeWidget.setGeometry(QtCore.QRect(10, 60, 151, 491))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/电脑.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/文档.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/视频.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon3)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/音乐.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon4)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/删除.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon5)
        self.progressBar = QtWidgets.QProgressBar(self.frameLeft)
        self.progressBar.setGeometry(QtCore.QRect(20, 570, 151, 15))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(180, 30, 691, 41))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 10, 75, 23))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/下载.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 10, 75, 23))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/分享.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 16))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 10, 75, 23))
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 10, 101, 23))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/网盘-新建文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon8)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 16))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 75, 23))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/上传.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(24, 16))
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(180, 80, 691, 41))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(520, 10, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(630, 10, 41, 23))
        self.pushButton_6.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/搜索.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon10)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 16))
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(180, 120, 691, 441))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(30, 10, 121, 81))
        self.frame_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_5.setAutoFillBackground(True)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/文件夹 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon11)
        self.pushButton_7.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_7.setAutoRepeatInterval(102)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(160, 10, 121, 81))
        self.frame_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_6.setAutoFillBackground(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon11)
        self.pushButton_8.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_8.setAutoRepeatInterval(102)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(290, 10, 121, 81))
        self.frame_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_7.setAutoFillBackground(True)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon11)
        self.pushButton_9.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_9.setAutoRepeatInterval(102)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(420, 10, 121, 81))
        self.frame_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_8.setAutoFillBackground(True)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_12.setAutoRepeatInterval(102)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(550, 10, 121, 81))
        self.frame_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_9.setAutoFillBackground(True)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon11)
        self.pushButton_13.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_13.setAutoRepeatInterval(102)
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(30, 90, 121, 81))
        self.frame_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_10.setAutoFillBackground(True)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon11)
        self.pushButton_11.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_11.setAutoRepeatInterval(102)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(160, 90, 121, 81))
        self.frame_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_11.setAutoFillBackground(True)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_14.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon11)
        self.pushButton_14.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_14.setAutoRepeatInterval(102)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 121, 81))
        self.frame_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_15.setAutoFillBackground(True)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_18.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_18.setText("")
        self.pushButton_18.setIcon(icon11)
        self.pushButton_18.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_18.setAutoRepeatInterval(102)
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        self.frame_16.setGeometry(QtCore.QRect(130, 0, 121, 81))
        self.frame_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_16.setAutoFillBackground(True)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_19.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon11)
        self.pushButton_19.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_19.setAutoRepeatInterval(102)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_13 = QtWidgets.QLabel(self.frame_16)
        self.label_13.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName("label_13")
        self.frame_17 = QtWidgets.QFrame(self.frame_11)
        self.frame_17.setGeometry(QtCore.QRect(260, 0, 121, 81))
        self.frame_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_17.setAutoFillBackground(True)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon11)
        self.pushButton_20.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_20.setAutoRepeatInterval(102)
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_14 = QtWidgets.QLabel(self.frame_17)
        self.label_14.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.frame_18 = QtWidgets.QFrame(self.frame_11)
        self.frame_18.setGeometry(QtCore.QRect(390, 0, 121, 81))
        self.frame_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_18.setAutoFillBackground(True)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon11)
        self.pushButton_21.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_21.setAutoRepeatInterval(102)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_15 = QtWidgets.QLabel(self.frame_18)
        self.label_15.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.frame_19 = QtWidgets.QFrame(self.frame_11)
        self.frame_19.setGeometry(QtCore.QRect(520, 0, 121, 81))
        self.frame_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_19.setAutoFillBackground(True)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_22.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_22.setText("")
        self.pushButton_22.setIcon(icon11)
        self.pushButton_22.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_22.setAutoRepeatInterval(102)
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_16 = QtWidgets.QLabel(self.frame_19)
        self.label_16.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setObjectName("label_16")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setGeometry(QtCore.QRect(290, 90, 121, 81))
        self.frame_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_12.setAutoFillBackground(True)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon11)
        self.pushButton_15.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_15.setAutoRepeatInterval(102)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setGeometry(QtCore.QRect(420, 90, 121, 81))
        self.frame_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_13.setAutoFillBackground(True)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon11)
        self.pushButton_16.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_16.setAutoRepeatInterval(102)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setGeometry(QtCore.QRect(550, 90, 121, 81))
        self.frame_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_14.setAutoFillBackground(True)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setText("")
        self.pushButton_17.setIcon(icon11)
        self.pushButton_17.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_17.setAutoRepeatInterval(102)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.frame_20 = QtWidgets.QFrame(self.frame_3)
        self.frame_20.setGeometry(QtCore.QRect(420, 170, 121, 81))
        self.frame_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_20.setAutoFillBackground(True)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_23.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_23.setText("")
        self.pushButton_23.setIcon(icon11)
        self.pushButton_23.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_23.setAutoRepeatInterval(102)
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        self.label_17.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName("label_17")
        self.frame_21 = QtWidgets.QFrame(self.frame_3)
        self.frame_21.setGeometry(QtCore.QRect(290, 170, 121, 81))
        self.frame_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_21.setAutoFillBackground(True)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_24.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_24.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_24.setText("")
        self.pushButton_24.setIcon(icon11)
        self.pushButton_24.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_24.setAutoRepeatInterval(102)
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_18 = QtWidgets.QLabel(self.frame_21)
        self.label_18.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setObjectName("label_18")
        self.frame_22 = QtWidgets.QFrame(self.frame_3)
        self.frame_22.setGeometry(QtCore.QRect(160, 170, 121, 81))
        self.frame_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_22.setAutoFillBackground(True)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_25.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_25.setText("")
        self.pushButton_25.setIcon(icon11)
        self.pushButton_25.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_25.setAutoRepeatInterval(102)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_19 = QtWidgets.QLabel(self.frame_22)
        self.label_19.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setObjectName("label_19")
        self.frame_23 = QtWidgets.QFrame(self.frame_3)
        self.frame_23.setGeometry(QtCore.QRect(30, 170, 121, 81))
        self.frame_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_23.setAutoFillBackground(True)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_26.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_26.setText("")
        self.pushButton_26.setIcon(icon11)
        self.pushButton_26.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_26.setAutoRepeatInterval(102)
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_20 = QtWidgets.QLabel(self.frame_23)
        self.label_20.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setObjectName("label_20")
        self.frame_24 = QtWidgets.QFrame(self.frame_3)
        self.frame_24.setGeometry(QtCore.QRect(550, 170, 121, 81))
        self.frame_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_24.setAutoFillBackground(True)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_27.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_27.setText("")
        self.pushButton_27.setIcon(icon11)
        self.pushButton_27.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_27.setAutoRepeatInterval(102)
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_21 = QtWidgets.QLabel(self.frame_24)
        self.label_21.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setObjectName("label_21")
        self.frame_25 = QtWidgets.QFrame(self.frame_3)
        self.frame_25.setGeometry(QtCore.QRect(420, 250, 121, 81))
        self.frame_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_25.setAutoFillBackground(True)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_33.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_33.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_33.setText("")
        self.pushButton_33.setIcon(icon11)
        self.pushButton_33.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_33.setAutoRepeatInterval(102)
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_27 = QtWidgets.QLabel(self.frame_25)
        self.label_27.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setObjectName("label_27")
        self.frame_26 = QtWidgets.QFrame(self.frame_3)
        self.frame_26.setGeometry(QtCore.QRect(290, 250, 121, 81))
        self.frame_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_26.setAutoFillBackground(True)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_34.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_34.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_34.setText("")
        self.pushButton_34.setIcon(icon11)
        self.pushButton_34.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_34.setAutoRepeatInterval(102)
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_28 = QtWidgets.QLabel(self.frame_26)
        self.label_28.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setObjectName("label_28")
        self.frame_27 = QtWidgets.QFrame(self.frame_3)
        self.frame_27.setGeometry(QtCore.QRect(160, 250, 121, 81))
        self.frame_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_27.setAutoFillBackground(True)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_35.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_35.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_35.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_35.setText("")
        self.pushButton_35.setIcon(icon11)
        self.pushButton_35.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_35.setAutoRepeatInterval(102)
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_29 = QtWidgets.QLabel(self.frame_27)
        self.label_29.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setObjectName("label_29")
        self.frame_28 = QtWidgets.QFrame(self.frame_3)
        self.frame_28.setGeometry(QtCore.QRect(550, 250, 121, 81))
        self.frame_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_28.setAutoFillBackground(True)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_36.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_36.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_36.setText("")
        self.pushButton_36.setIcon(icon11)
        self.pushButton_36.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_36.setAutoRepeatInterval(102)
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_30 = QtWidgets.QLabel(self.frame_28)
        self.label_30.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_30.setTextFormat(QtCore.Qt.AutoText)
        self.label_30.setObjectName("label_30")
        self.frame_29 = QtWidgets.QFrame(self.frame_3)
        self.frame_29.setGeometry(QtCore.QRect(30, 250, 121, 81))
        self.frame_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_29.setAutoFillBackground(True)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButton_37 = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_37.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_37.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_37.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_37.setText("")
        self.pushButton_37.setIcon(icon11)
        self.pushButton_37.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_37.setAutoRepeatInterval(102)
        self.pushButton_37.setObjectName("pushButton_37")
        self.label_31 = QtWidgets.QLabel(self.frame_29)
        self.label_31.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_31.setObjectName("label_31")
        self.frame_32 = QtWidgets.QFrame(self.frame_3)
        self.frame_32.setGeometry(QtCore.QRect(160, 330, 121, 81))
        self.frame_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_32.setAutoFillBackground(True)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.pushButton_40 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_40.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_40.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_40.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_40.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_40.setText("")
        self.pushButton_40.setIcon(icon11)
        self.pushButton_40.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_40.setAutoRepeatInterval(102)
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_34 = QtWidgets.QLabel(self.frame_32)
        self.label_34.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_34.setTextFormat(QtCore.Qt.AutoText)
        self.label_34.setObjectName("label_34")
        self.frame_33 = QtWidgets.QFrame(self.frame_3)
        self.frame_33.setGeometry(QtCore.QRect(300, 330, 121, 81))
        self.frame_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_33.setAutoFillBackground(True)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.pushButton_41 = QtWidgets.QPushButton(self.frame_33)
        self.pushButton_41.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_41.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_41.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_41.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Desktop/矢量图/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_41.setIcon(icon12)
        self.pushButton_41.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_41.setAutoRepeatInterval(102)
        self.pushButton_41.setObjectName("pushButton_41")
        self.label_35 = QtWidgets.QLabel(self.frame_33)
        self.label_35.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_35.setTextFormat(QtCore.Qt.AutoText)
        self.label_35.setObjectName("label_35")
        self.frame_34 = QtWidgets.QFrame(self.frame_3)
        self.frame_34.setGeometry(QtCore.QRect(30, 330, 121, 81))
        self.frame_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_34.setAutoFillBackground(True)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.pushButton_42 = QtWidgets.QPushButton(self.frame_34)
        self.pushButton_42.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.pushButton_42.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_42.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_42.setText("")
        self.pushButton_42.setIcon(icon11)
        self.pushButton_42.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_42.setAutoRepeatInterval(102)
        self.pushButton_42.setObjectName("pushButton_42")
        self.label_36 = QtWidgets.QLabel(self.frame_34)
        self.label_36.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_36.setTextFormat(QtCore.Qt.AutoText)
        self.label_36.setObjectName("label_36")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "家庭数据中心"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "我的电脑"))
        list=psutil.disk_partitions()
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "C盘"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "D盘"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "E盘"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "F盘"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "数据中心"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "图片"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "视频"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "音乐"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "回收站"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_2.setText(_translate("MainWindow", "下载"))
        self.pushButton_3.setText(_translate("MainWindow", "分享"))
        self.pushButton_4.setText(_translate("MainWindow", "删除"))
        self.pushButton_5.setText(_translate("MainWindow", "新建文件夹"))
        self.pushButton.setText(_translate("MainWindow", "上传"))
        self.label.setText(_translate("MainWindow", "文件"))
        self.label_2.setText(_translate("MainWindow", "文件"))
        self.label_3.setText(_translate("MainWindow", "文件"))
        self.label_6.setText(_translate("MainWindow", "文件"))
        self.label_7.setText(_translate("MainWindow", "文件"))
        self.label_5.setText(_translate("MainWindow", "文件"))
        self.label_8.setText(_translate("MainWindow", "文件"))
        self.label_12.setText(_translate("MainWindow", "文件"))
        self.label_13.setText(_translate("MainWindow", "文件"))
        self.label_14.setText(_translate("MainWindow", "文件"))
        self.label_15.setText(_translate("MainWindow", "文件"))
        self.label_16.setText(_translate("MainWindow", "文件"))
        self.label_9.setText(_translate("MainWindow", "文件"))
        self.label_10.setText(_translate("MainWindow", "文件"))
        self.label_11.setText(_translate("MainWindow", "文件"))
        self.label_17.setText(_translate("MainWindow", "文件"))
        self.label_18.setText(_translate("MainWindow", "文件"))
        self.label_19.setText(_translate("MainWindow", "文件"))
        self.label_20.setText(_translate("MainWindow", "文件"))
        self.label_21.setText(_translate("MainWindow", "文件"))
        self.label_27.setText(_translate("MainWindow", "文件"))
        self.label_28.setText(_translate("MainWindow", "文件"))
        self.label_29.setText(_translate("MainWindow", "文件"))
        self.label_30.setText(_translate("MainWindow", "文件"))
        self.label_31.setText(_translate("MainWindow", "文件"))
        self.label_34.setText(_translate("MainWindow", "文件"))
        self.label_35.setText(_translate("MainWindow", "文件"))
        self.label_36.setText(_translate("MainWindow", "文件"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


